services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: house-work-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: house_work_scheduler
      MYSQL_USER: housework
      MYSQL_PASSWORD: housework123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - house-work-network
    command: --default-authentication-plugin=mysql_native_password

  # Backend API
  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
      target: production
    container_name: house-work-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USERNAME: housework
      MYSQL_PASSWORD: housework123
      MYSQL_DATABASE: house_work_scheduler
      PORT: 3001
      NOTION_DATABASE_ID: ${NOTION_DATABASE_ID:-}
      NOTION_TOKEN: ${NOTION_TOKEN}
      NOTION_VERSION: ${NOTION_VERSION:-2022-06-28}
      FRONTEND_URL: http://localhost:3002
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    networks:
      - house-work-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend
  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
      target: production
    container_name: house-work-frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:3001}
    ports:
      - "3002:3002"
    depends_on:
      - backend
    networks:
      - house-work-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3002"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mysql_data:
    driver: local

networks:
  house-work-network:
    driver: bridge
