services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: house-work-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: house-work-scheduler
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - house-work-network

  # Backend API
  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
      target: production
    container_name: house-work-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/house-work-scheduler?authSource=admin
      PORT: 3001
      NOTION_DATABASE_ID: ${NOTION_DATABASE_ID:-}
      NOTION_TOKEN: ${NOTION_TOKEN}
      NOTION_VERSION: ${NOTION_VERSION:-2022-06-28}
      FRONTEND_URL: http://localhost:3002
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    networks:
      - house-work-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend
  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
      target: production
    container_name: house-work-frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:3001}
    ports:
      - "3002:3002"
    depends_on:
      - backend
    networks:
      - house-work-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3002"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongodb_data:
    driver: local

networks:
  house-work-network:
    driver: bridge
